[all:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios 
ansible_connection=network_cli
ansible_become_method=enable
ansible_become=yes
ansible_command_timeout=2400    # instead of default 30
ansible_ssh_timeout=120

[site1_switches_baseline] # Targets only GCC  NPOC switches dot1x config
NPOC_Switch ansible_host=10.88.108.90
NPOC_SWITCH_95k ansible_host=10.88.108.66
cbxtpdc-04-c94as11_94K ansible_host=10.88.108.75

[site2_switches_baseline]
cticblrm4scas01-cp94 ansible_host=10.220.0.12
; [npoc_switches_baseline:vars]
; ansible_user={{ ansible_user_npoc }}
; ansible_password={{ ansible_password_npoc }}